### PR TITLE
Mention python package dependencies

### PR DESCRIPTION
**Pull request by ender503**
Use the 'requirements.txt' to declare and install the Python package
dependencies.

### CODE REVIEW

**Comment by jserv** [comment]
Is it necessary to install all the packages described in file ` requirements.txt`? Can we simplify the dependency list?

**Comment by ender503** [comment]
No, it is not necessary to install packages by `requirements.txt`, but it would be better to have it.
And `requirements.txt` is a common way to install the python package dependencies.
[Building a Python Project - Travis CI](https://docs.travis-ci.com/user/languages/python/)

**Comment by ender503** [comment]
I'll try to simplify the dependency list in the `requirements.txt`.

**Comment by jserv** [comment]
@ender503, ping?

**Comment by ender503** [comment]
@jserv, thanks for your reminder.
I update the `requirements.txt` file. 👍

**Comment by ender503** [comment]
@jserv, thanks for your reminder.
I update the `requirements.txt` file. 👍

**Pull request merged**
